name: Deploy

on: [push]

jobs:
  deploy:
    name: deploy/Vercel
    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Deployment with github actions
        uses: amondnet/vercel-action@v20
        id: vercel-action-deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Find the current PR
        uses: jwalton/gh-find-current-pr@v1
        id: pr-finder
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Retrieve preview URL
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.pr-finder.outputs.number }}
          recreate: true
          message: |
            **The latest updates on your projects.**
            | **Name** | **Preview** |
            | -------- | ----------- |
            | **${{ steps.vercel-action-deploy.outputs.preview-name }}** | [Visit Preview](${{ steps.vercel-action-deploy.outputs.preview-url }}) |
