name: Deploy

on: [push]

jobs:
  deploy:
    name: deploy/Vercel
    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Deployment with github actions
        uses: amondnet/vercel-action@v20
        id: vercel_preview_url
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Retrieve preview URL
        run: echo "https://${{ steps.vercel_preview_url.outputs.preview-url }}"
