name: Lint

on: [push]

jobs:
  linter:
    name: Run linter for identifying and reporting on the patterns
    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node and cache yarn dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '16.15.0'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Run linter
        run: yarn lint
