name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node and cache yarn dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '16.15.0'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Run linter
        run: yarn lint

      - name: Run test
        run: yarn test --coverage --watchAll=false --ci
